/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pianoroll;
import com.jsyn.JSyn;
import com.jsyn.Synthesizer;
import com.jsyn.unitgen.LineOut;
import com.jsyn.unitgen.SineOscillator;

/**
 *
 * @author adriano
 */
public class Additive extends javax.swing.JFrame {

    Synthesizer synth;
    SineOscillator osc1;
    SineOscillator osc2;
    SineOscillator osc3;
    LineOut lineOut;

    /**
     * Creates new form Additive
     */
    public Additive() {
        initComponents();
        initSynth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSliderFreq1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jSliderAmp1 = new javax.swing.JSlider();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSliderFreq2 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jSliderAmp2 = new javax.swing.JSlider();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSliderFreq3 = new javax.swing.JSlider();
        jLabel16 = new javax.swing.JLabel();
        jSliderAmp3 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sin1"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Freq (100-5000Hz):");
        jPanel1.add(jLabel1);

        jSliderFreq1.setMaximum(5000);
        jSliderFreq1.setMinimum(100);
        jSliderFreq1.setValue(300);
        jSliderFreq1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderFreq1StateChanged(evt);
            }
        });
        jPanel1.add(jSliderFreq1);

        jLabel2.setText("Amp (0-100%):");
        jPanel1.add(jLabel2);

        jSliderAmp1.setValue(0);
        jSliderAmp1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderAmp1StateChanged(evt);
            }
        });
        jPanel1.add(jSliderAmp1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Sin2"));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Freq (100-5000Hz):");
        jPanel5.add(jLabel9);

        jSliderFreq2.setMaximum(5000);
        jSliderFreq2.setMinimum(100);
        jSliderFreq2.setValue(700);
        jSliderFreq2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderFreq2StateChanged(evt);
            }
        });
        jPanel5.add(jSliderFreq2);

        jLabel10.setText("Amp (0-100%):");
        jPanel5.add(jLabel10);

        jSliderAmp2.setValue(0);
        jSliderAmp2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderAmp2StateChanged(evt);
            }
        });
        jPanel5.add(jSliderAmp2);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Sin3"));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Freq (100-5000Hz):");
        jPanel8.add(jLabel15);

        jSliderFreq3.setMaximum(5000);
        jSliderFreq3.setMinimum(100);
        jSliderFreq3.setValue(1000);
        jSliderFreq3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderFreq3StateChanged(evt);
            }
        });
        jPanel8.add(jSliderFreq3);

        jLabel16.setText("Amp (0-100%):");
        jPanel8.add(jLabel16);

        jSliderAmp3.setValue(0);
        jSliderAmp3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderAmp3StateChanged(evt);
            }
        });
        jPanel8.add(jSliderAmp3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderAmp1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderAmp1StateChanged
        while (jSliderAmp1.getValue() + jSliderAmp2.getValue() + jSliderAmp3.getValue() > 100) {
            jSliderAmp2.setValue(jSliderAmp2.getValue() - 1);
            jSliderAmp3.setValue(jSliderAmp3.getValue() - 1);
        }
        osc1.amplitude.set((double)jSliderAmp1.getValue() / 100);
    }//GEN-LAST:event_jSliderAmp1StateChanged

    private void jSliderAmp2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderAmp2StateChanged
        while (jSliderAmp1.getValue() + jSliderAmp2.getValue() + jSliderAmp3.getValue() > 100) {
            jSliderAmp1.setValue(jSliderAmp1.getValue() - 1);
            jSliderAmp3.setValue(jSliderAmp3.getValue() - 1);
        }
        System.out.println((double)jSliderAmp2.getValue() / 100);
        osc2.amplitude.set((double)jSliderAmp2.getValue() / 100);
    }//GEN-LAST:event_jSliderAmp2StateChanged

    private void jSliderAmp3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderAmp3StateChanged
        while (jSliderAmp1.getValue() + jSliderAmp2.getValue() + jSliderAmp3.getValue() > 100) {
            jSliderAmp1.setValue(jSliderAmp1.getValue() - 1);
            jSliderAmp2.setValue(jSliderAmp2.getValue() - 1);
        }
        osc3.amplitude.set((double)jSliderAmp3.getValue() / 100);
    }//GEN-LAST:event_jSliderAmp3StateChanged

    private void jSliderFreq1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderFreq1StateChanged
        osc1.frequency.set((double)jSliderFreq1.getValue());
    }//GEN-LAST:event_jSliderFreq1StateChanged

    private void jSliderFreq2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderFreq2StateChanged
        osc2.frequency.set((double)jSliderFreq2.getValue());
    }//GEN-LAST:event_jSliderFreq2StateChanged

    private void jSliderFreq3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderFreq3StateChanged
        osc3.frequency.set((double)jSliderFreq3.getValue());
    }//GEN-LAST:event_jSliderFreq3StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Additive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Additive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Additive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Additive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Additive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider6;
    private javax.swing.JSlider jSlider7;
    private javax.swing.JSlider jSliderAmp1;
    private javax.swing.JSlider jSliderAmp2;
    private javax.swing.JSlider jSliderAmp3;
    private javax.swing.JSlider jSliderFreq1;
    private javax.swing.JSlider jSliderFreq2;
    private javax.swing.JSlider jSliderFreq3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    private void initSynth() {
        synth = JSyn.createSynthesizer();
        synth.add(osc1 = new SineOscillator() );
        synth.add(osc2 = new SineOscillator() );
        synth.add(osc3 = new SineOscillator() );
        synth.add(lineOut = new LineOut());

        osc1.getOutput().connect(0, lineOut.input, 0);
        osc1.getOutput().connect(0, lineOut.input, 1);
        osc2.getOutput().connect(0, lineOut.input, 0);
        osc2.getOutput().connect(0, lineOut.input, 1);
        osc3.getOutput().connect(0, lineOut.input, 0);
        osc3.getOutput().connect(0, lineOut.input, 1);
        
        osc1.frequency.set((double)jSliderFreq1.getValue());
        osc2.frequency.set((double)jSliderFreq2.getValue());
        osc3.frequency.set((double)jSliderFreq3.getValue());

        osc1.amplitude.set((double)jSliderAmp1.getValue() / 100);
        osc2.amplitude.set((double)jSliderAmp2.getValue() / 100);
        osc3.amplitude.set((double)jSliderAmp3.getValue() / 100);

        synth.start();
        lineOut.start();
    }
   
}
